# Generative AI Used: GitHub Copilot (GitHub/OpenAI)
# Purpose: Copilot was used during development to generate suggestions for bug fixes
# and to provide some structural suggestions while writing parts of the code.
# Prompt/Context: Suggestions were automatically generated by Copilot within
# the editor while coding.
import argparse
import hashlib
import os
import struct
import csv

SECTOR_SIZE = 512


def compute_hashes(file_path, verbose=False):
    if verbose:
        print("Calculating MD5, SHA-256, and SHA-512 hashes...")

    md5 = hashlib.md5()
    sha256 = hashlib.sha256()
    sha512 = hashlib.sha512()

    with open(file_path, "rb") as f:
        while chunk := f.read(4096):
            md5.update(chunk)
            sha256.update(chunk)
            sha512.update(chunk)

    filename = os.path.basename(file_path)
    base = os.path.splitext(filename)[0]

    with open(f"MD5-{base}.txt", "w") as f:
        f.write(md5.hexdigest())

    with open(f"SHA-256-{base}.txt", "w") as f:
        f.write(sha256.hexdigest())

    with open(f"SHA-512-{base}.txt", "w") as f:
        f.write(sha512.hexdigest())

    if verbose:
        print("Hashes written to files.")


def load_partition_types():
    partition_types = {}
    try:
        with open("partition_types.csv", newline='', encoding="utf-8") as f:
            reader = csv.reader(f)
            next(reader)
            for row in reader:
                partition_types[row[1].lower()] = row[2]
    except:
        pass
    return partition_types


def detect_partition_scheme(f, verbose=False):
    if verbose:
        print("Detecting partition scheme...")

    f.seek(0)
    mbr = f.read(SECTOR_SIZE)

    for i in range(4):
        entry = mbr[446 + i*16 : 446 + (i+1)*16]
        ptype = entry[4]
        if ptype == 0xEE:
            f.seek(SECTOR_SIZE)
            if f.read(8) == b"EFI PART":
                if verbose:
                    print("Partition scheme detected: GPT")
                return "GPT"

    if verbose:
        print("Partition scheme detected: MBR")

    return "MBR"


def parse_mbr(f, offsets, partition_types, verbose=False):
    if verbose:
        print("Reading MBR partition table...")

    f.seek(0)
    mbr = f.read(SECTOR_SIZE)

    partitions = []

    for i in range(4):
        entry = mbr[446 + i*16 : 446 + (i+1)*16]

        ptype = entry[4]
        if ptype == 0x00:
            continue

        start_lba = struct.unpack("<I", entry[8:12])[0]
        size = struct.unpack("<I", entry[12:16])[0]

        hex_type = f"{ptype:02x}"
        name = partition_types.get(hex_type, "Unknown")

        print(f"({hex_type.upper()}), {name}, {start_lba}, {size}")

        partitions.append((start_lba, i+1))

    for idx, (start_lba, pnum) in enumerate(partitions):
        if idx >= len(offsets):
            break

        offset = offsets[idx]

        if verbose:
            print(f"Reading boot record for partition {pnum} at offset {offset}")

        f.seek(start_lba * SECTOR_SIZE)
        sector = f.read(SECTOR_SIZE)

        data = sector[offset:offset+16]

        hex_values = " ".join(f"{b:02x}" for b in data)

        ascii_values = "  ".join(chr(b) if 32 <= b <= 126 else "." for b in data)

        print(f"Partition number: {pnum}")
        print(f"16 bytes of boot record from offset {offset}: {hex_values}")
        print(f"ASCII:                                    {ascii_values}")


def parse_gpt(f, verbose=False):
    if verbose:
        print("Reading GPT header...")

    f.seek(SECTOR_SIZE)
    header = f.read(SECTOR_SIZE)

    part_lba = struct.unpack("<Q", header[72:80])[0]
    num_entries = struct.unpack("<I", header[80:84])[0]
    entry_size = struct.unpack("<I", header[84:88])[0]

    if verbose:
        print("GPT partition entries start at LBA:", part_lba)

    f.seek(part_lba * SECTOR_SIZE)

    partition_number = 1

    for _ in range(num_entries):
        entry = f.read(entry_size)

        part_type_guid = entry[0:16]

        if part_type_guid == b"\x00"*16:
            continue

        first_lba = struct.unpack("<Q", entry[32:40])[0]
        last_lba = struct.unpack("<Q", entry[40:48])[0]

        name = entry[56:128].decode("utf-16le").rstrip("\x00")

        size_bytes = (last_lba - first_lba + 1) * SECTOR_SIZE

        guid = part_type_guid.hex().upper()

        print(f"Partition number: {partition_number}")
        print(f"Partition Type GUID : {guid}")
        print(f"Starting LBA in hex: {hex(first_lba)}")
        print(f"ending LBA in hex: {hex(last_lba)}")
        print(f"starting LBA in Decimal: {first_lba}")
        print(f"ending LBA in Decimal: {last_lba}")
        print(f"Partition name: {name}")
        print(f"Partition size in bytes: {size_bytes}")
        print()

        partition_number += 1


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-f", required=True, help="Raw disk image")
    parser.add_argument("-o", nargs="*", type=int, default=[], help="Offsets for MBR partitions")
    parser.add_argument("--verbose", action="store_true", help="Enable verbose output")

    args = parser.parse_args()

    if args.verbose:
        print("Opening disk image:", args.f)

    compute_hashes(args.f, args.verbose)

    partition_types = load_partition_types()

    with open(args.f, "rb") as f:
        scheme = detect_partition_scheme(f, args.verbose)

        if scheme == "MBR":
            parse_mbr(f, args.o, partition_types, args.verbose)
        else:
            parse_gpt(f, args.verbose)


if __name__ == "__main__":
    main()
